schema: './playground/schema.graphql'
documents:
  - './playground/pages/**/*.graphql'
  - './playground/components/**/*.graphql'
  - './playground/composables/**/*.graphql'
  - './playground/plugins/**/*.graphql'
